
  - alias: 'Turn outside garage lights on evening'
    trigger:
      platform: sun
      event: sunset
    action:
      - delay: '+00:{{ (range(15, 45)|random|int) }}:00'
      - service: homeassistant.turn_on
        entity_id: switch.garage_outside_light_switch

  - alias: 'Turn outside garage lights off evening'
    trigger:
      platform: time
      at: "23:00:00"
    action:
      - delay: '+00:{{ (range(1, 59)|random|int) }}:00'
      - service: homeassistant.turn_off
        entity_id: switch.garage_outside_light_switch

  - alias: 'Turn outside garage lights on Morning'
    trigger:
      platform: time
      at: "04:15:00"
    action:
      service: homeassistant.turn_on
      entity_id:
        - switch.garage_outside_light_switch
        - switch.front_door_light_switch

  - alias: 'Turn outside garage lighs off Morning'
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:30:00"
    action:
      service: homeassistant.turn_off
      entity_id:
        - switch.garage_outside_light_switch
        - switch.front_door_light_switch

  - alias: 'Dining Room Lights On'
    trigger:
      platform: state
      to: 'on'
      entity_id:
        - switch.dining_room_light_other_switch
        - switch.dining_room_light_main_switch
    action:
      service: homeassistant.turn_on
      entity_id:
        - switch.dining_room_light_other_switch
        - switch.dining_room_light_main_switch

  - alias: 'Dining Room Lights Off'
    trigger:
      platform: state
      to: 'off'
      entity_id:
        - switch.dining_room_light_other_switch
        - switch.dining_room_light_main_switch
    action:
      service: homeassistant.turn_off
      entity_id:
        - switch.dining_room_light_other_switch
        - switch.dining_room_light_main_switch

  - alias: 'Vacation - Turn living room lights on Evening'
    initial_state: False
    trigger:
      platform: sun
      event: sunset
    action:
      - delay: '+00:{{ (range(1, 59)|random|int) }}:00'
      - service: homeassistant.turn_on
        entity_id: light.living_room_dimm_level

  - alias: 'Vacation - Turn living rooms lights off Evening'
    initial_state: False
    trigger:
      platform: time
      at: "22:00:00"
    action:
      - delay: '01:{{ (range(1, 59)|random|int) }}:00'
      - service: homeassistant.turn_off
        entity_id: light.living_room_dimm_level

  - alias: 'Vacation - Turn Bedroom On after Living Room off'
    initial_state: False
    trigger:
      platform: state
      to: 'off'
      entity_id: light.living_room_dimm_level
    action:
      - service: homeassistant.turn_on
        entity_id: light.master_bedroom_dimm_level

  - alias: 'Vacation - Turn Bedroom Off'
    initial_state: False    
    trigger:
      platform: state
      to: 'on'
      entity_id: light.master_bedroom_dimm_level
    action:
      - delay: '00:{{ (range(15, 45)|random|int) }}:00'
      - service: homeassistant.turn_on
        entity_id: light.master_bedroom_dimm_level

  - alias: 'Garage Door Open'
    trigger:
      - platform: state
        entity_id: sensor.alarm_status
        to: 'Armed'
        for: 
          minutes: '5'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.garage_door2
        state: 'Open'
      - condition: state
        entity_id: binary_sensor.ecolink_tilt_sensor_sensor
        state: 'on'
    action:
      - service: notify.PB
        data_template:
          message: "Hey Jackass, check the garage!!!!"

  - alias: 'Turn on lights when home after sunset'
    trigger:
      - platform: state
        entity_id: sensor.alarm_status
        to: 'Disarmed'
    condition:
      - condition: sun
        after: sunset
    action:
      - service: homeassistant.turn_on
        entity_id: light.living_room_couch_dimm_level