
  - alias: 'Turn outside garage lights on evening'
    trigger:
      platform: sun
      event: sunset
    action:
      - delay: '+00:{{ (range(15, 45)|random|int) }}:00'
      - service: homeassistant.turn_on
        entity_id: switch.garage_outside_light_switch

  - alias: 'Turn outside garage lights off evening'
    trigger:
      platform: time
      at: "23:00:00"
    action:
      - delay: +00:{{ (range(1, 59)|random|int) }}:00'
      - service: homeassistant.turn_off
        entity_id: switch.garage_outside_light_switch

  - alias: 'Turn outside garage lights on Morning'
    trigger:
      platform: time
      at: "04:15:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.garage_outside_light_switch

  - alias: 'Turn outside garage lighs off Morning'
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:30:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.garage_outside_light_switch

  - alias: 'Dining Room Lights On'
    trigger:
      platform: state
      to: 'on'
      entity_id:
        - switch.dining_room_light_other_switch
        - switch.dining_room_light_main_switch
    action:
      service: homeassistant.turn_on
      entity_id:
        - switch.dining_room_light_other_switch
        - switch.dining_room_light_main_switch

  - alias: 'Dining Room Lights Off'
    trigger:
      platform: state
      to: 'off'
      entity_id:
        - switch.dining_room_light_other_switch
        - switch.dining_room_light_main_switch
    action:
      service: homeassistant.turn_off
      entity_id:
        - switch.dining_room_light_other_switch
        - switch.dining_room_light_main_switch

  - alias: 'Vacation - Turn living room lights on Evening'
    trigger:
      platform: sun
      event: sunset
    action:
      - delay: '+00:{{ (range(1, 59)|random|int) }}:00'
      - service: homeassistant.turn_on
        entity_id: light.living_room_dimm_level

  - alias: 'Vacation - Turn living rooms lights off Evening'
    trigger:
      platform: time
      at: "22:00:00"
    action:
      - delay: '01:{{ (range(1, 59)|random|int) }}:00'
      - service: homeassistant.turn_off
        entity_id: light.living_room_dimm_level

  - alias: 'Vacation - Turn Bedroom On after Living Room off'
    trigger:
      platform: state
      to: 'off'
      entity_id: light.living_room_dimm_level
    action:
      - service: homeassistant.turn_on
        entity_id: light.bedroom_dimm_level

  - alias: 'Vacation - Turn Bedroom Off'
    trigger:
      platform: state
      to: 'on'
      entity_id: light.bedroom_dimm_level
    action:
      - delay: '00:{{ (range(15, 45)|random|int) }}:00'
      - service: homeassistant.turn_on
        entity_id: light.bedroom_dimm_level

  - alias: 'Delay test'
    trigger:
      platform: state
      to: 'on'
      entity_id: light.living_room_dimm_level
    action:
      - delay: '00:{{ (range(2, 4)|random|int) }}:00'
      - service: homeassistant.turn_off
        entity_id: light.living_room_dimm_level

  - alias: 'Alert when alarm away and garage door open'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_panel
        to: 'armed_home'
        from: 'disarmed'

    condition:
      condition: or
      conditions:
        - platform: state
          entity_id: cover.garage_door_main_controller_open
          state: 'open'
          for: 00:01:00
        - platform: state
          entity_id: binary_sensor.ecolink_tilt_sensor_sensor
          state: 'on'
          for: 00:01:00

    action:
      - service: notify.PB
        data_template:
          message: "Hey Jackass, check the garage!!!!"

  - alias: 'Notify test'
    trigger:
      platform: time
      at: '20:07:00'
    action:
      service: notify.PB
      data_template:
        message: "test message"