  - alias: 'Turn outside garage lights on'
    trigger:
      platform: sun
      event: sunset
      #offset: '+00:45:00'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.garage_outside_light_switch_5_0
      - delay: '+00:{{ (range(15, 45)|random|int) }}:00'

  - alias: 'Turn outside garage lights off'
    trigger:
      platform: time
      after: "23:00:00"
    action:
      - service: homeassistant.turn_off
        entity_id: switch.garage_outside_light_switch_5_0
      - delay: +00:{{ (range(1, 59)|random|int) }}:00'
  - alias: 'Turn outside garage lights on Morning'
    trigger:
      platform: time
      after: "04:15:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.garage_outside_light_switch_5_0

  - alias: 'Turn outside garage lighs off Morning'
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:30:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.garage_outside_light_switch_5_0

  - alias: 'Dining Room Lights On'
    trigger:
      platform: state
      state: 'on'
      entity_id:
        - switch.dining_room_light_other_switch_17_0
        - switch.dining_room_light_main_switch_16_0
    action:
      service: homeassistant.turn_on
      entity_id:
        - switch.dining_room_light_other_switch_17_0
        - switch.dining_room_light_main_switch_16_0

  - alias: 'Dining Room Lights Off'
    trigger:
      platform: state
      state: 'off'
      entity_id:
        - switch.dining_room_light_other_switch_17_0
        - switch.dining_room_light_main_switch_16_0
    action:
      service: homeassistant.turn_off
      entity_id:
        - switch.dining_room_light_other_switch_17_0
        - switch.dining_room_light_main_switch_16_0

  - alias: 'Vacation - Turn living room lights on Evening'
    trigger:
      platform: sun
      event: sunset
    action:
      - service: homeassistant.turn_on
        entity_id: light.living_room_dimm_level_3_0
      - delay: '+00:{{ (range(1, 59)|random|int) }}:00'

  - alias: 'Vacation - Turn living rooms lights off Evening'
    trigger:
      platform: time
      after: "22:00:00"
    action:
      - service: homeassistant.turn_off
        entity_id: light.living_room_dimm_level_3_0
      - delay: '01:{{ (range(1, 59)|random|int) }}:00'

  - alias: 'Vacation - Turn Bedroom On after Living Room off'
    trigger:
      platform: state
      state: 'off'
      entity_id: light.living_room_dimm_level_3_0
    action:
      - service: homeassistant.turn_on
        entity_id: light.bedroom_dimm_level_18_0

   - alias: 'Vacation - Turn Bedroom Off'
     trigger:
       platform: state
       state: 'on'
       entity_id: light.bedroom_dimm_level_18_0
    action:
      - service: homeassistant.turn_on
        entity_id: light.bedroom_dimm_level_18_0
      - delay: '00:{{ (range(15, 45)|random|int) }}:00'
