homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#  customize:
#    light.living_room_dimm_level_3_0:
#      emulated_hue_name: "living room light"

  time_zone: America/New_York

  #customize: !include customize.yaml

map:

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 100

  - name: Gym
    latitude: !secret gym_lat
    longitude: !secret gym_long
    radius: 100

  - name: Clinic
    latitude: !secret clinic_lat
    longitude: !secret clinic_long
    radius: 100

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key 

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

#recorder:
#  purge_interval: 1
#  purge_keep_days: 21
#  db_url: !secret recorder_db_url

  
# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - icon
      - summary
      - precip_intensity
      - precip_probability
      - temperature
      - temperature_max
      - temperature_min
      - wind_speed
      - wind_bearing
      - visibility
      - apparent_temperature
      - minutely_summary
      - hourly_summary
      - daily_summary
      - dew_point
      - cloud_cover
      - humidity

  - platform: pi_hole
    host: 10.0.0.152

#  - platform: speedtest
#    server_id: !secret speedtest_server_id
#      - ping
#      - download
#      - upload

  - platform: plex
    host: 10.0.0.158

  - platform: template
    sensors:
      anyone_home:
        value_template: "{% if is_state('device_tracker.mike_android', 'home') or is_state('device_tracker.84ac0ddb496b49c7ab4f427dbb271c72', 'home')-%}home{%else%}not_home{% endif %}"

  - platform: template
    sensors:
      garage_door:
        value_template: "{{ states.cover.garage_door_main_controller_open == 'closed' }}"

  - platform: template
    sensors:
      garage_door2:
        value_template: "{% if is_state('cover.garage_door_main_controller_open', 'open') %}Open{% elif is_state('cover.garage_door_main_controller_open', 'closed') %}Closed{%else%}ERROR{% endif %}" 

  - platform: template
    sensors:
      alarm_status:
        value_template: "{% if is_state('sensor.alarm_panel_display', 'ARMED ***AWAY***** ALL SECURE **') or is_state('sensor.alarm_panel_display', 'ARMED ***STAY***                ') %}Armed{%else%}Disarmed{% endif %}"

# Text to speech
#tts:
#  platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

zwave:
  usb_path: /dev/ttyACM0
#  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config 
  polling_interval: 30000
  device_config_domain:
    light:
      polling_intensity: 1
      refresh_value: true
      delay: 3

cover:
  platform: zwave

media_player:
  - platform: firetv
    device: livingroom
    host: 10.0.0.106
    port: 5556
    name: FireTV - Living Room
  - platform: plex

notify:
  - name: PB
    platform: pushbullet
    api_key: !secret pb_api_key

  - platform: nfandroidtv
    name: Vizio
    host: 10.0.0.108
    duration: 6
    position: center

#service: logger.set_level
#data:
#  homeassistant.components: debug
logger:
  default: debug
  logs:
    #homeassistant.components.automation: debug
    #homeassistant.components.switch.broadlink: info
    homeassistant.components: debug
    homeassistant.components.alarmdecoder: debug
    homeassistant.components.alarm_decoder: debug
    homeassistant.components.alarm_control_panel: debug
    
switch:
  # - platform: broadlink
  #   host: 10.0.0.131
  #   mac: '34:EA:34:BB:10:4D'
  #   switches:
  #     tv:
  #       command_on: 'JgBQAAABIZATEhISEjcSEhITEhMSEhITEjYUNBMSEjYTNhI2EjYTNhISEzYSEhI3EhISNxISExISNhMSEjYSExI2EhMSNhI3EgAFgAABIUgSAA0FAAAAAAAAAAA='
  #       command_off: 'JgBQAAABI44UERISFDUUEBITEhMTERITFDQUNBITFDQSNxM1FDQUNRQ0FBETNRISExISNhQRFBETERQ0FBEUNBQ1FBAUNRQ0FAAFfQABI0YUAA0FAAAAAAAAAAA='
  #     tvbak:
  #       command_on: 'JgBQAAABK5IVEBUQFTUVEBUQFRAVERUQFTUVNRUQFTYVNRU1FTUVNhUQFRAVEBU1FREVEBUQFRAVNRU1FTYVEBU1FTUVNhU1FQAFBQABKEsSAA0FAAAAAAAAAAA='
  #       command_off: 'JgBQAAABK5IVEBUQFTUVEBUQFRAVERUQFTUVNRUQFTYVNRU1FTUVNhUQFRAVEBU1FREVEBUQFRAVNRU1FTYVEBU1FTUVNhU1FQAFBQABKEsSAA0FAAAAAAAAAAA='
  #     volume:
  #       command_on: 'JgBYAAABKZMTExMSEzcUERMSExITEhQSEzcUNhMSEzgUNhM3EzgTNxQREzcUERQSExIUERQRExITOBQRFDYUNhQ3FDYUNhQ2FAAFBwABKUoUAAxHAAEpShMADQU='
  #       command_off: 'JgBQAAABKZMTEhMSEzgTEhMSExITEhMSEzgTNxMSEzcTOBM3EzcTNxMSEzgTEhMSExITEhMSExIUNxMSEzcTNxM4EzcTNxM3EwAFCAABKEoTAA0FAAAAAAAAAAA='
  - platform: template
    switches:
      bedtime:
        value_template: "{{ is_state('switch.bedtime', 'on')}}"
        turn_on:
          service: script.bedtime
        turn_off:
          service: script.bedtime

  - platform: rachio
    access_token: !secret rachio_access_token

alarmdecoder: !include alarmdecoder.yaml
automation: !include automation.yaml
group: !include group.yaml
script: !include script.yaml

camera:
  - platform: generic
    still_image_url: https://maps.darksky.net/@radar,27.520,-82.561,10
    name: radar

  - platform: zoneminder

zoneminder:
  host: 10.0.0.118

influxdb:
  host: 10.0.0.123

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key
  #expose_by_default: true
  exposed_domains:
    - switch
    - scene
    - light
    - script
  entity_config:
    light.living_room_couch_dimm_level:
      name: "couch light"
    light.master_bedroom_dimm_level:
      name: "bedroom light"
    light.living_room_ceiling_dimm_level:
      name: "ceiling light"
    light.kitchen_ceiling_dimm_level:
      name: "kitchen light"
    group.dining_room_lights:
      name: "dining room lights"
    switch.christmas_tree_switch:
      name: "christmas tree"

device_tracker:
  - platform: gpslogger
  - platform: locative

panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump

