default_view:
  view: yes
  entities:
    #- automation.update_available_notification
    - group.general
    - group.alarm
    - group.climate
    - group.automation
    - group.vacation_automation
    - group.alarm_zones
    - group.garage_doors
    - group.lights
    - group.climate_forecast
    - group.forecast_group
    - group.tv

general:
  name: General
  entities:
    - sensor.date
    - sensor.time
    - sensor.moon

alarm:
  name: Alarm
  entities:
    - alarm_control_panel.alarm_panel
    - sensor.alarm_panel_display
    - input_select.alarm_mode

automation:
  name: Automation
  entities:
    - automation.dining_room_lights_on
    - automation.dining_room_lights_off
    - automation.turn_outside_garage_lights_on_morning
    - automation.turn_outside_garage_lighs_off_morning
    - automation.turn_outside_garage_lights_on_evening
    - automation.turn_outside_garage_lights_off_evening
    - automation.alert_when_alarm_away_and_garage_door_open
    - automation.notify_test

vacation_automation:
  name: Vacation Automation
  entities:
    - automation.vacation__turn_living_room_lights_on_evening
    - automation.vacation__turn_living_rooms_lights_off_evening
    - automation.vacation__turn_bedroom_on_after_living_room_off
    - automation.vacation__turn_bedroom_off

alarm_zones:
  name: Alarm Zones
  view: yes
  entities:
    - binary_sensor.bedroom_1_window
    - binary_sensor.bedroom_2_window
    - binary_sensor.family_rm_sliding_door
    - binary_sensor.front_door
#    - binary_sensor.kitchen_motion
    - binary_sensor.kitchen_sliding_door
    - binary_sensor.kitchen_windows
    - binary_sensor.laundry_room_door
    - binary_sensor.living_rm_windows
    - binary_sensor.master_sliding_door
    - binary_sensor.master_windows
    - binary_sensor.office_window
    - binary_sensor.smoke_detector

garage_doors:
  name: Garage Doors
  entities:
    - cover.garage_door_main_controller_open
    - binary_sensor.ecolink_tilt_sensor_sensor

lights:
  name: Lights
  entities:
    - light.living_room_ceiling_dimm_level
    - light.living_room_couch_dimm_level
    - light.master_bedroom_dimm_level
    - switch.dining_room_light_main_switch
    - switch.dining_room_light_other_switch
    - switch.garage_outside_light_switch
    - switch.front_door_light_switch

climate_group:
  name: Climate
  entities:
    - climate.home
    - sensor.dark_sky_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_summary
    - sensor.dark_sky_dew_point
    - sensor.dark_sky_humidity
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_wind_bearing
    - sensor.dark_sky_visibility
    - sensor.dark_sky_cloud_coverage

climate_forecast:
  name: Forecast
  view: no
  control: no
  entities:
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_daily_summary
    - camera.radar
    
TV:
  name: TV
  entities:
    - switch.tv

Dining_Room_Lights:
  name: Dining Rooms Lights
  entities:
    - switch.dining_room_light_main_switch
    - switch.dining_room_light_other_switch