default_view:
  view: yes
  entities:
    #- automation.update_available_notification
    - group.general
    - group.alarm
    - group.climate
    - group.automation
    - group.vacation_automation
    - group.alarm_zones
    - group.garage_doors
    - group.lights
    - group.climate_forecast
    - group.forecast_group
    - group.tv
    - group.garage_doors
    #- group.owntracks
    #- group.plex
    - media_player.fire_tv
    #- sensor.plex

general:
  name: General
  entities:
    - sensor.date
    - sensor.time
    - sensor.moon

alarm:
  name: Alarm
  entities:
    - alarm_control_panel.alarm_panel
    - sensor.alarm_panel_display
    - input_select.alarm_mode

automation:
  name: Automation
  entities:
    - automation.dining_room_lights_on
    - automation.dining_room_lights_off
    - automation.turn_front_door_light_on_morning
    - automation.turn_front_door_light_off_morning
    - automation.turn_outside_garage_lights_on_evening
    - automation.turn_outside_garage_lights_off_morning
    - automation.garage_door_open
    - automation.turn_on_christmas_tree

vacation_automation:
  name: Vacation Automation
  entities:
    - automation.vacation__turn_living_room_lights_on_evening
    - automation.vacation__turn_living_rooms_lights_off_evening
    - automation.vacation__turn_bedroom_on_after_living_room_off
    - automation.vacation__turn_bedroom_off

alarm_zones:
  name: Alarm Zones
  view: yes
  entities:
    - binary_sensor.bedroom_1_window
    - binary_sensor.bedroom_2_window
    - binary_sensor.family_rm_sliding_door
    - binary_sensor.front_door
#    - binary_sensor.kitchen_motion
    - binary_sensor.kitchen_sliding_door
    - binary_sensor.kitchen_windows
    - binary_sensor.laundry_room_door
    - binary_sensor.living_rm_windows
    - binary_sensor.master_sliding_door
    - binary_sensor.master_windows
    - binary_sensor.office_window
    - binary_sensor.smoke_detector

garage_doors:
  name: Garage Doors
  entities:
    - binary_sensor.main_garage_tilt_sensor
    - binary_sensor.second_garage_tilt_sensor

lights:
  name: Lights
  entities:
    - light.living_room_ceiling_dimm_level
    - light.living_room_couch_dimm_level
    - light.master_bedroom_dimm_level
    - light.kitchen_ceiling_dimm_level
    - switch.dining_room_light_main_switch
    - switch.dining_room_light_other_switch
    - switch.garage_outside_light_switch
    - switch.front_door_light_switch
    - switch.christmas_tree_switch
    
climate_group:
  name: Climate
  entities:
    - climate.home
    - sensor.dark_sky_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_summary
    - sensor.dark_sky_dew_point
    - sensor.dark_sky_humidity
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_wind_bearing
    - sensor.dark_sky_visibility
    - sensor.dark_sky_cloud_coverage

climate_forecast:
  name: Forecast
  view: yes
  entities:
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_daily_summary
    - camera.radar
    - weather.darksky

TV:
  name: TV
  entities:
    - switch.tv

Dining_Room_Lights:
  name: Dining Rooms Lights
  entities:
    - switch.dining_room_light_main_switch
    - switch.dining_room_light_other_switch

Zoneminder:
  name: Zoneminder
  view: yes
  entities:
    - camera.front_door
    - camera.driveway

Plex:
  name: Plex
  view: no
  entities:
    - media_player.fire_tv

# Owntracks:
#   name: Device Tracker
#   entities:
#     - device_tracker.04157df488e6bc01
#     - device_tracker.3b967280ca6ea98
#     - device_tracker.84ac0ddb496b49c7ab4f427dbb271c72