default_view:
  view: yes
  entities:
    #- automation.update_available_notification
    - group.general
    - group.alarm
    - group.climate
    - group.automation
    - group.vacation_automation
    - group.alarm_zones
    - group.garage_doors
    - group.lights

general:
  name: General
  entities:
    - sensor.date
    - sensor.time
    - sensor.moon

alarm:
  name: Alarm
  entities:
    - alarm_control_panel.alarm_panel
    - sensor.alarm_panel_display
    - input_select.alarm_mode

climate:
  name: Climate
  entities:
    - climate.hallway
    - sensor.hallway_thermostat_humidity
    - sensor.hallway_thermostat_hvac_state
    - sensor.hallway_thermostat_operation_mode
    - sensor.hallway_thermostat_target
    - sensor.hallway_thermostat_temperature
    - sensor.yweather_temperature
    - sensor.yweather_humidity
    - sensor.yweather_current
    - sensor.yweather_condition

automation:
  name: Automation
  entities:
    - automation.dining_room_lights_on
    - automation.dining_room_lights_off
    - automation.turn_outside_garage_lights_on_morning
    - automation.turn_outside_garage_lighs_off_morning
    - automation.turn_outside_garage_lights_on_evening
    - automation.turn_outside_garage_lights_off_evening

vacation_automation:
  name: Vacation Automation
  entities:
    - automation.vacation__turn_living_room_lights_on_evening
    - automation.vacation__turn_living_rooms_lights_off_evening
    - automation.vacation__turn_bedroom_on_after_living_room_off
    - automation.vacation__turn_bedroom_off

alarm_zones:
  name: Alarm Zones
  entities:
    - binary_sensor.bedroom_1_window
    - binary_sensor.bedroom_2_window
    - binary_sensor.family_rm_sliding_door
    - binary_sensor.front_door
    - binary_sensor.kitchen_motion
    - binary_sensor.kitchen_sliding_door
    - binary_sensor.kitchen_windows
    - binary_sensor.laundry_room_door
    - binary_sensor.living_rm_windows
    - binary_sensor.master_sliding_door
    - binary_sensor.master_windows
    - binary_sensor.office_window
    - binary_sensor.smoke_detector

garage_doors:
  name: Garage Doors
  entities:
    - cover.garage_door_main_controller_open
    - binary_sensor.ecolink_tilt_sensor_sensor

lights:
  name: Lights
  entities:
    - light.living_room_dimm_level
    - switch.dining_room_light_main_switch
    - switch.dining_room_light_other_switch
    - switch.garage_outside_light_switch